<?php

namespace ContainerFa8ZvnR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LTM1UQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LTM1U_q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LTM1U_q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.LTM1U_q.App\\Entity\\Articles', NULL, 'Cannot autowire service ".service_locator.LTM1U_q": it references class "App\\Entity\\Articles" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'article' => 'App\\Entity\\Articles',
            'entityManager' => '?',
        ]);
    }
}
