<?php

namespace ContainerFa8ZvnR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WBiSglmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WBiSglm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WBiSglm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'rating' => ['privates', '.errored..service_locator.WBiSglm.App\\Entity\\Rating', NULL, 'Cannot autowire service ".service_locator.WBiSglm": it references class "App\\Entity\\Rating" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'rating' => 'App\\Entity\\Rating',
        ]);
    }
}
