<?php

namespace ContainerE8QrxB7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VWjyy73Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VWjyy73' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VWjyy73'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UsersController::add' => ['privates', '.service_locator.1oueM0n', 'get_ServiceLocator_1oueM0nService', true],
            'App\\Controller\\UsersController::delete' => ['privates', '.service_locator.YdtL5XU', 'get_ServiceLocator_YdtL5XUService', true],
            'App\\Controller\\UsersController::edit' => ['privates', '.service_locator.uyeIuaL', 'get_ServiceLocator_UyeIuaLService', true],
            'App\\Controller\\UsersController::editForAdmin' => ['privates', '.service_locator.uyeIuaL', 'get_ServiceLocator_UyeIuaLService', true],
            'App\\Controller\\UsersController::edita' => ['privates', '.service_locator.uyeIuaL', 'get_ServiceLocator_UyeIuaLService', true],
            'App\\Controller\\UsersController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UsersController::new' => ['privates', '.service_locator.1oueM0n', 'get_ServiceLocator_1oueM0nService', true],
            'App\\Controller\\UsersController::newForAdmin' => ['privates', '.service_locator.1oueM0n', 'get_ServiceLocator_1oueM0nService', true],
            'App\\Controller\\UsersController::show' => ['privates', '.service_locator.Sgq.tmb', 'get_ServiceLocator_Sgq_TmbService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UsersController:add' => ['privates', '.service_locator.1oueM0n', 'get_ServiceLocator_1oueM0nService', true],
            'App\\Controller\\UsersController:delete' => ['privates', '.service_locator.YdtL5XU', 'get_ServiceLocator_YdtL5XUService', true],
            'App\\Controller\\UsersController:edit' => ['privates', '.service_locator.uyeIuaL', 'get_ServiceLocator_UyeIuaLService', true],
            'App\\Controller\\UsersController:editForAdmin' => ['privates', '.service_locator.uyeIuaL', 'get_ServiceLocator_UyeIuaLService', true],
            'App\\Controller\\UsersController:edita' => ['privates', '.service_locator.uyeIuaL', 'get_ServiceLocator_UyeIuaLService', true],
            'App\\Controller\\UsersController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UsersController:new' => ['privates', '.service_locator.1oueM0n', 'get_ServiceLocator_1oueM0nService', true],
            'App\\Controller\\UsersController:newForAdmin' => ['privates', '.service_locator.1oueM0n', 'get_ServiceLocator_1oueM0nService', true],
            'App\\Controller\\UsersController:show' => ['privates', '.service_locator.Sgq.tmb', 'get_ServiceLocator_Sgq_TmbService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UsersController::add' => '?',
            'App\\Controller\\UsersController::delete' => '?',
            'App\\Controller\\UsersController::edit' => '?',
            'App\\Controller\\UsersController::editForAdmin' => '?',
            'App\\Controller\\UsersController::edita' => '?',
            'App\\Controller\\UsersController::index' => '?',
            'App\\Controller\\UsersController::new' => '?',
            'App\\Controller\\UsersController::newForAdmin' => '?',
            'App\\Controller\\UsersController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UsersController:add' => '?',
            'App\\Controller\\UsersController:delete' => '?',
            'App\\Controller\\UsersController:edit' => '?',
            'App\\Controller\\UsersController:editForAdmin' => '?',
            'App\\Controller\\UsersController:edita' => '?',
            'App\\Controller\\UsersController:index' => '?',
            'App\\Controller\\UsersController:new' => '?',
            'App\\Controller\\UsersController:newForAdmin' => '?',
            'App\\Controller\\UsersController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
