<?php

namespace ContainerK4PbKGb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OKdhJrHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OKdhJrH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OKdhJrH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ArticlesController::delete' => ['privates', '.service_locator.VA4WuTa', 'get_ServiceLocator_VA4WuTaService', true],
            'App\\Controller\\ArticlesController::edit' => ['privates', '.service_locator.VA4WuTa', 'get_ServiceLocator_VA4WuTaService', true],
            'App\\Controller\\ArticlesController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ArticlesController::indexFront' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ArticlesController::indexadmin' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ArticlesController::new' => ['privates', '.service_locator.dRYsSss', 'get_ServiceLocator_DRYsSssService', true],
            'App\\Controller\\ArticlesController::show' => ['privates', '.service_locator.5oWwBc.', 'get_ServiceLocator_5oWwBc_Service', true],
            'App\\Controller\\GaleriesController::delete' => ['privates', '.service_locator.CHTeqWB', 'get_ServiceLocator_CHTeqWBService', true],
            'App\\Controller\\GaleriesController::delete1' => ['privates', '.service_locator.CHTeqWB', 'get_ServiceLocator_CHTeqWBService', true],
            'App\\Controller\\GaleriesController::edit' => ['privates', '.service_locator.CHTeqWB', 'get_ServiceLocator_CHTeqWBService', true],
            'App\\Controller\\GaleriesController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\GaleriesController::new' => ['privates', '.service_locator.dRYsSss', 'get_ServiceLocator_DRYsSssService', true],
            'App\\Controller\\GaleriesController::show' => ['privates', '.service_locator.LeQo8VS', 'get_ServiceLocator_LeQo8VSService', true],
            'App\\Controller\\PanierController::delete' => ['privates', '.service_locator.3A1P0Yq', 'get_ServiceLocator_3A1P0YqService', true],
            'App\\Controller\\PanierController::edit' => ['privates', '.service_locator.3A1P0Yq', 'get_ServiceLocator_3A1P0YqService', true],
            'App\\Controller\\PanierController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PanierController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PanierController::show' => ['privates', '.service_locator.QMLTBp2', 'get_ServiceLocator_QMLTBp2Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ArticlesController:delete' => ['privates', '.service_locator.VA4WuTa', 'get_ServiceLocator_VA4WuTaService', true],
            'App\\Controller\\ArticlesController:edit' => ['privates', '.service_locator.VA4WuTa', 'get_ServiceLocator_VA4WuTaService', true],
            'App\\Controller\\ArticlesController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ArticlesController:indexFront' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ArticlesController:indexadmin' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ArticlesController:new' => ['privates', '.service_locator.dRYsSss', 'get_ServiceLocator_DRYsSssService', true],
            'App\\Controller\\ArticlesController:show' => ['privates', '.service_locator.5oWwBc.', 'get_ServiceLocator_5oWwBc_Service', true],
            'App\\Controller\\GaleriesController:delete' => ['privates', '.service_locator.CHTeqWB', 'get_ServiceLocator_CHTeqWBService', true],
            'App\\Controller\\GaleriesController:delete1' => ['privates', '.service_locator.CHTeqWB', 'get_ServiceLocator_CHTeqWBService', true],
            'App\\Controller\\GaleriesController:edit' => ['privates', '.service_locator.CHTeqWB', 'get_ServiceLocator_CHTeqWBService', true],
            'App\\Controller\\GaleriesController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\GaleriesController:new' => ['privates', '.service_locator.dRYsSss', 'get_ServiceLocator_DRYsSssService', true],
            'App\\Controller\\GaleriesController:show' => ['privates', '.service_locator.LeQo8VS', 'get_ServiceLocator_LeQo8VSService', true],
            'App\\Controller\\PanierController:delete' => ['privates', '.service_locator.3A1P0Yq', 'get_ServiceLocator_3A1P0YqService', true],
            'App\\Controller\\PanierController:edit' => ['privates', '.service_locator.3A1P0Yq', 'get_ServiceLocator_3A1P0YqService', true],
            'App\\Controller\\PanierController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PanierController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PanierController:show' => ['privates', '.service_locator.QMLTBp2', 'get_ServiceLocator_QMLTBp2Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ArticlesController::delete' => '?',
            'App\\Controller\\ArticlesController::edit' => '?',
            'App\\Controller\\ArticlesController::index' => '?',
            'App\\Controller\\ArticlesController::indexFront' => '?',
            'App\\Controller\\ArticlesController::indexadmin' => '?',
            'App\\Controller\\ArticlesController::new' => '?',
            'App\\Controller\\ArticlesController::show' => '?',
            'App\\Controller\\GaleriesController::delete' => '?',
            'App\\Controller\\GaleriesController::delete1' => '?',
            'App\\Controller\\GaleriesController::edit' => '?',
            'App\\Controller\\GaleriesController::index' => '?',
            'App\\Controller\\GaleriesController::new' => '?',
            'App\\Controller\\GaleriesController::show' => '?',
            'App\\Controller\\PanierController::delete' => '?',
            'App\\Controller\\PanierController::edit' => '?',
            'App\\Controller\\PanierController::index' => '?',
            'App\\Controller\\PanierController::new' => '?',
            'App\\Controller\\PanierController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ArticlesController:delete' => '?',
            'App\\Controller\\ArticlesController:edit' => '?',
            'App\\Controller\\ArticlesController:index' => '?',
            'App\\Controller\\ArticlesController:indexFront' => '?',
            'App\\Controller\\ArticlesController:indexadmin' => '?',
            'App\\Controller\\ArticlesController:new' => '?',
            'App\\Controller\\ArticlesController:show' => '?',
            'App\\Controller\\GaleriesController:delete' => '?',
            'App\\Controller\\GaleriesController:delete1' => '?',
            'App\\Controller\\GaleriesController:edit' => '?',
            'App\\Controller\\GaleriesController:index' => '?',
            'App\\Controller\\GaleriesController:new' => '?',
            'App\\Controller\\GaleriesController:show' => '?',
            'App\\Controller\\PanierController:delete' => '?',
            'App\\Controller\\PanierController:edit' => '?',
            'App\\Controller\\PanierController:index' => '?',
            'App\\Controller\\PanierController:new' => '?',
            'App\\Controller\\PanierController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
