<?php

namespace ContainerK4PbKGb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGaleriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CHTeqWB.App\Entity\Galeries' shared service.
     *
     * @return \App\Entity\Galeries
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CHTeqWB": it references class "App\\Entity\\Galeries" but no such service exists.');
    }
}
