<?php

namespace ContainerVIu6fEU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CHTeqWBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CHTeqWB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CHTeqWB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'flashy' => ['services', 'mercuryseries_flashy.flashy_notifier', 'getMercuryseriesFlashy_FlashyNotifierService', true],
            'galery' => ['privates', '.errored..service_locator.CHTeqWB.App\\Entity\\Galeries', NULL, 'Cannot autowire service ".service_locator.CHTeqWB": it references class "App\\Entity\\Galeries" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'flashy' => '?',
            'galery' => 'App\\Entity\\Galeries',
        ]);
    }
}
