<?php

namespace ContainerFp4aJu1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ri2a06Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6ri2a06' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ri2a06'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored.UHYLg98', NULL, 'Cannot determine controller argument for "App\\Controller\\ArticlesController::showComments()": the $article argument is type-hinted with the non-existent class or interface: "App\\Controller\\Article". Did you forget to add a use statement?'],
        ], [
            'article' => '?',
        ]);
    }
}
