<?php

namespace ContainerFp4aJu1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_UHYLg98Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.UHYLg98' shared service.
     *
     * @return \App\Controller\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ArticlesController::showComments()": the $article argument is type-hinted with the non-existent class or interface: "App\\Controller\\Article". Did you forget to add a use statement?');
    }
}
