<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNo7ycU5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNo7ycU5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNo7ycU5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNo7ycU5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNo7ycU5\App_KernelDevDebugContainer([
    'container.build_hash' => 'No7ycU5',
    'container.build_id' => '79282b67',
    'container.build_time' => 1682962761,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNo7ycU5');
