<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYY72W2g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYY72W2g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYY72W2g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYY72W2g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYY72W2g\App_KernelDevDebugContainer([
    'container.build_hash' => 'YY72W2g',
    'container.build_id' => 'fb51bc94',
    'container.build_time' => 1682229442,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYY72W2g');
