<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerNo7ycU5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNo7ycU5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNo7ycU5.legacy');
=======
if (\class_exists(\Container78kQApk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container78kQApk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container78kQApk.legacy');
>>>>>>> origin/integration

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerNo7ycU5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNo7ycU5\App_KernelDevDebugContainer([
    'container.build_hash' => 'No7ycU5',
    'container.build_id' => '79282b67',
    'container.build_time' => 1682962761,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNo7ycU5');
=======
    \class_alias(\Container78kQApk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container78kQApk\App_KernelDevDebugContainer([
    'container.build_hash' => '78kQApk',
    'container.build_id' => 'e0d55112',
    'container.build_time' => 1682413153,
], __DIR__.\DIRECTORY_SEPARATOR.'Container78kQApk');
>>>>>>> origin/integration
